server:
  port: 8080

spring:
  application:
    name:
      socket-java
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${socket.datasource.host}:${socket.datasource.port}/${socket.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: ${socket.datasource.driver-class-name}
    username: ${socket.datasource.username}
    password: ${socket.datasource.password}
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.socket.socketjava.domain.pojo
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql