server:
  port: 8080

spring:
  application:
    name:
      socket-java
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${socket.datasource.host}:${socket.datasource.port}/${socket.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: ${socket.datasource.driver-class-name}
    username: ${socket.datasource.username}
    password: ${socket.datasource.password}
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.socket.socketjava.domain.pojo
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

aliyun:
  oss:
    endpoint: ${aliyun.oss.endpoint}  # 替换为你的 OSS 服务 endpoint
    accessKeyId: ${aliyun.oss.accessKeyId}        # 替换为你的 AccessKeyId
    accessKeySecret: ${aliyun.oss.accessKeySecret} # 替换为你的 AccessKeySecret
    bucketName: ${aliyun.oss.bucketName}           # 替换为你的 Bucket 名称